export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_AlERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR'
export const CLOSE_NAVBAR = 'CLOSE_NAVBAR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const SELECT_DATE_APPOINTMENT = 'SELECT_DATE_APPOINTMENT'
export const TILEDISABLED = 'TILEDISABLED'

export const SHOW_TIME = 'SHOW_TIME'
export const NO_SHOW_TIME = 'NO_SHOW_TIME'

export const SELECT_TIME_APPOINTMENT = 'SELECT_TIME_APPOINTMENT'

export const CREATE_APPOINTMENT_BEGIN = 'CREATE_APPOINTMENT_BEGIN'
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS'
export const CREATE_APPOINTMENT_ERROR = 'CREATE_APPOINTMENT_ERROR'

export const DELETE_APPOINTMENT_BEGIN = 'DELETE_APPOINTMENT_BEGIN'

export const SHOW_INFOS_PROFILE_BEGIN = 'SHOW_INFOS_PROFILE_BEGIN'
export const SHOW_INFOS_PROFILE_SUCCESS = 'SHOW_INFOS_PROFILE_SUCCESS'

export const SHOW_APPOINTMENTS_BEGIN = 'SHOW_APPOINTMENTS_BEGIN'
export const SHOW_APPOINTMENTS_SUCCESS = 'SHOW_APPOINTMENTS_SUCCESS'

export const GET_APPOINTMENTS_ALLREADY_BOOKED_BEGIN = 'GET_APPOINTMENTS_ALLREADY_BOOKED_BEGIN'
export const GET_APPOINTMENTS_ALLREADY_BOOKED_SUCCESS = 'GET_APPOINTMENTS_ALLREADY_BOOKED_SUCCESS'


export const SHOW_EDIT_PROFILE = 'SHOW_EDIT_PROFILE'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_SLIDER_AVATAR = 'HANDLE_SLIDER_AVATAR'
export const HANDLE_CANCEL_AVATAR = 'HANDLE_CANCEL_AVATAR'
export const HANDLE_FILE_CHANGE_AVATAR = 'HANDLE_FILE_CHANGE_AVATAR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
